openapi: 3.0.1
info:
  title: Equipment Systems
  version: '1.0'
servers:
  - url: https://api-integration.servicetitan.io/equipmentsystems/v2
paths:
  '/tenant/{tenant}/installed-equipment':
    get:
      tags:
        - InstalledEquipment
      summary: InstalledEquipment_GetList
      operationId: InstalledEquipment_GetList
      parameters:
        - name: tenant
          in: path
          description: Tenant ID
          required: true
          schema:
            type: integer
        - name: locationIds
          in: query
          schema:
            type: string
        - name: ids
          in: query
          schema:
            type: string
        - name: createdBefore
          in: query
          description: Format - date-time (as date-time in RFC3339).
          schema:
            type: string
            format: date-time
            nullable: true
        - name: createdOnOrAfter
          in: query
          description: Format - date-time (as date-time in RFC3339).
          schema:
            type: string
            format: date-time
            nullable: true
        - name: modifiedBefore
          in: query
          description: Format - date-time (as date-time in RFC3339).
          schema:
            type: string
            format: date-time
            nullable: true
        - name: modifiedOnOrAfter
          in: query
          description: Format - date-time (as date-time in RFC3339).
          schema:
            type: string
            format: date-time
            nullable: true
        - name: page
          in: query
          description: Format - int32.
          schema:
            type: integer
            format: int32
            nullable: true
        - name: pageSize
          in: query
          description: Format - int32.
          schema:
            type: integer
            format: int32
            nullable: true
        - name: includeTotal
          in: query
          schema:
            type: boolean
            nullable: true
        - name: sort
          in: query
          description: "Applies sorting by the specified field:\\\n\"?sort=+FieldName\" for ascending order,\\\n\"?sort=-FieldName\" for descending order.\\\n\\\nAvailable fields are: Id, CreatedOn, ModifiedOn."
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedResponse_Of_EquipmentSystems.V2.InstalledEquipmentResponse'
              example:
                page: 0
                pageSize: 0
                hasMore: true
                totalCount: 0
                data:
                  - id: 0
                    locationId: 0
                    customerId: 0
                    name: string
                    installedOn: string
                    serialNumber: string
                    memo: string
                    manufacturer: string
                    model: string
                    cost: 0
                    manufacturerWarrantyStart: string
                    manufacturerWarrantyEnd: string
                    serviceProviderWarrantyStart: string
                    serviceProviderWarrantyEnd: string
        '400':
          description: 'The request cannot be processed, check validation errors or request format'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                type: string
                title: string
                status: 0
                traceId: string
                errors: { }
                data: { }
    post:
      tags:
        - InstalledEquipment
      summary: InstalledEquipment_Create
      operationId: InstalledEquipment_Create
      parameters:
        - name: tenant
          in: path
          description: Tenant ID
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EquipmentSystems.V2.InstalledEquipmentCreateRequest'
            example:
              locationId: 0
              name: string
              installedOn: string
              serialNumber: string
              memo: string
              manufacturer: string
              model: string
              cost: 0
              manufacturerWarrantyStart: string
              manufacturerWarrantyEnd: string
              serviceProviderWarrantyStart: string
              serviceProviderWarrantyEnd: string
              customFields:
                - id: 0
                  typeId: 0
                  value: string
      responses:
        '200':
          description: The request has succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EquipmentSystems.V2.InstalledEquipmentDetailedResponse'
              example:
                id: 0
                locationId: 0
                customerId: 0
                name: string
                installedOn: string
                serialNumber: string
                memo: string
                manufacturer: string
                model: string
                cost: 0
                manufacturerWarrantyStart: string
                manufacturerWarrantyEnd: string
                serviceProviderWarrantyStart: string
                serviceProviderWarrantyEnd: string
                customFields:
                  - id: 0
                    typeId: 0
                    name: string
                    value: string
        '400':
          description: 'The request cannot be processed, check validation errors or request format'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                type: string
                title: string
                status: 0
                traceId: string
                errors: { }
                data: { }
  '/tenant/{tenant}/installed-equipment/{id}':
    get:
      tags:
        - InstalledEquipment
      summary: InstalledEquipment_Get
      operationId: InstalledEquipment_Get
      parameters:
        - name: id
          in: path
          description: Format - int64.
          required: true
          schema:
            type: integer
            format: int64
        - name: tenant
          in: path
          description: Tenant ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The request has succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EquipmentSystems.V2.InstalledEquipmentDetailedResponse'
              example:
                id: 0
                locationId: 0
                customerId: 0
                name: string
                installedOn: string
                serialNumber: string
                memo: string
                manufacturer: string
                model: string
                cost: 0
                manufacturerWarrantyStart: string
                manufacturerWarrantyEnd: string
                serviceProviderWarrantyStart: string
                serviceProviderWarrantyEnd: string
                customFields:
                  - id: 0
                    typeId: 0
                    name: string
                    value: string
        '400':
          description: 'The request cannot be processed, check validation errors or request format'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                type: string
                title: string
                status: 0
                traceId: string
                errors: { }
                data: { }
        '404':
          description: The requested entity was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                type: string
                title: string
                status: 0
                traceId: string
                errors: { }
                data: { }
    patch:
      tags:
        - InstalledEquipment
      summary: InstalledEquipment_Update
      operationId: InstalledEquipment_Update
      parameters:
        - name: id
          in: path
          description: Format - int64.
          required: true
          schema:
            type: integer
            format: int64
        - name: tenant
          in: path
          description: Tenant ID
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EquipmentSystems.V2.InstalledEquipmentUpdateRequest'
            example:
              name: string
              installedOn: string
              serialNumber: string
              memo: string
              manufacturer: string
              model: string
              cost: 0
              manufacturerWarrantyStart: string
              manufacturerWarrantyEnd: string
              serviceProviderWarrantyStart: string
              serviceProviderWarrantyEnd: string
              customFields:
                - id: 0
                  typeId: 0
                  value: string
      responses:
        '200':
          description: The request has succeeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EquipmentSystems.V2.InstalledEquipmentDetailedResponse'
              example:
                id: 0
                locationId: 0
                customerId: 0
                name: string
                installedOn: string
                serialNumber: string
                memo: string
                manufacturer: string
                model: string
                cost: 0
                manufacturerWarrantyStart: string
                manufacturerWarrantyEnd: string
                serviceProviderWarrantyStart: string
                serviceProviderWarrantyEnd: string
                customFields:
                  - id: 0
                    typeId: 0
                    name: string
                    value: string
        '400':
          description: 'The request cannot be processed, check validation errors or request format'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                type: string
                title: string
                status: 0
                traceId: string
                errors: { }
                data: { }
        '404':
          description: The requested entity was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
              example:
                type: string
                title: string
                status: 0
                traceId: string
                errors: { }
                data: { }
components:
  schemas:
    PaginatedResponse_Of_EquipmentSystems.V2.InstalledEquipmentResponse:
      required:
        - page
        - pageSize
        - hasMore
        - data
      type: object
      properties:
        page:
          type: integer
          description: From which page this output has started
          format: int32
        pageSize:
          type: integer
          description: Page size for this query (i.e. how many records were requested to return)
          format: int32
        hasMore:
          type: boolean
          description: True if there are more records in the query than returned in this result
        totalCount:
          type: integer
          description: Total count of records for this query (can optionally be populated)
          format: int32
          nullable: true
        data:
          type: array
          items:
            $ref: '#/components/schemas/EquipmentSystems.V2.InstalledEquipmentResponse'
          description: 'The collection of result items, will never have more than PageSize items'
      additionalProperties: false
      description: Represents paginated API response.
    EquipmentSystems.V2.InstalledEquipmentResponse:
      required:
        - id
        - locationId
        - customerId
        - name
        - serialNumber
        - memo
        - manufacturer
        - model
        - cost
      type: object
      properties:
        id:
          type: integer
          format: int64
        locationId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        name:
          type: string
        installedOn:
          type: string
          format: date-time
          nullable: true
        serialNumber:
          type: string
        memo:
          type: string
        manufacturer:
          type: string
        model:
          type: string
        cost:
          type: number
          format: decimal
        manufacturerWarrantyStart:
          type: string
          format: date-time
          nullable: true
        manufacturerWarrantyEnd:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyStart:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyEnd:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
    ApiErrorResponse:
      required:
        - type
        - title
        - status
        - traceId
        - errors
        - data
      type: object
      properties:
        type:
          type: string
          description: A URI reference that identifies the problem type
        title:
          type: string
          description: 'A short, human-readable summary of the problem type'
        status:
          type: integer
          description: The HTTP status code generated by server
          format: int32
        traceId:
          type: string
          description: Internal trace ID for advanced diagnostics
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: 'Provides more details about errors occurred, which can potentially be used for visual display'
        data:
          type: object
          additionalProperties: { }
          description: 'Provides additional data, intended for programmatical usage'
      additionalProperties: false
      description: 'Detailed error response, following RFC 7807 recommendations (https://tools.ietf.org/html/rfc7807).'
    EquipmentSystems.V2.InstalledEquipmentDetailedResponse:
      required:
        - id
        - locationId
        - customerId
        - name
        - serialNumber
        - memo
        - manufacturer
        - model
        - cost
      type: object
      properties:
        id:
          type: integer
          format: int64
        locationId:
          type: integer
          format: int64
        customerId:
          type: integer
          format: int64
        name:
          type: string
        installedOn:
          type: string
          format: date-time
          nullable: true
        serialNumber:
          type: string
        memo:
          type: string
        manufacturer:
          type: string
        model:
          type: string
        cost:
          type: number
          format: decimal
        manufacturerWarrantyStart:
          type: string
          format: date-time
          nullable: true
        manufacturerWarrantyEnd:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyStart:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyEnd:
          type: string
          format: date-time
          nullable: true
        customFields:
          type: array
          items:
            $ref: '#/components/schemas/EquipmentSystems.V2.CustomFieldResponseModel'
          nullable: true
      additionalProperties: false
    EquipmentSystems.V2.CustomFieldResponseModel:
      required:
        - id
        - typeId
      type: object
      properties:
        id:
          type: integer
          format: int64
        typeId:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        value:
          type: string
          nullable: true
      additionalProperties: false
    EquipmentSystems.V2.InstalledEquipmentCreateRequest:
      required:
        - locationId
      type: object
      properties:
        locationId:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        installedOn:
          type: string
          format: date-time
          nullable: true
        serialNumber:
          type: string
          nullable: true
        memo:
          type: string
          nullable: true
        manufacturer:
          type: string
          nullable: true
        model:
          type: string
          nullable: true
        cost:
          type: number
          format: decimal
          nullable: true
        manufacturerWarrantyStart:
          type: string
          format: date-time
          nullable: true
        manufacturerWarrantyEnd:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyStart:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyEnd:
          type: string
          format: date-time
          nullable: true
        customFields:
          type: array
          items:
            $ref: '#/components/schemas/EquipmentSystems.V2.CustomFieldRequestModel'
          nullable: true
      additionalProperties: false
    EquipmentSystems.V2.CustomFieldRequestModel:
      type: object
      properties:
        id:
          type: integer
          format: int64
          nullable: true
        typeId:
          type: integer
          format: int64
          nullable: true
        value:
          type: string
          nullable: true
      additionalProperties: false
    EquipmentSystems.V2.InstalledEquipmentUpdateRequest:
      type: object
      properties:
        name:
          type: string
        installedOn:
          type: string
          format: date-time
          nullable: true
        serialNumber:
          type: string
        memo:
          type: string
        manufacturer:
          type: string
        model:
          type: string
        cost:
          type: number
          format: decimal
          nullable: true
        manufacturerWarrantyStart:
          type: string
          format: date-time
          nullable: true
        manufacturerWarrantyEnd:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyStart:
          type: string
          format: date-time
          nullable: true
        serviceProviderWarrantyEnd:
          type: string
          format: date-time
          nullable: true
        customFields:
          type: array
          items:
            $ref: '#/components/schemas/EquipmentSystems.V2.CustomFieldRequestModel'
      additionalProperties: false
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: ST-App-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: servicetitanapplicationkey
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]